environment:
  TCI_DEBUG_MODE: 'true'
  TCI_PIPELINES_BRANCH: '${TCI_PIPELINES_BRANCH}'
  TCI_APP_SET_BRANCH: '${TCI_APP_SET_BRANCH}'
  TCI_DEFAULT_JDK_TOOL_NAME: 'jdk'
  TCI_DEFAULT_MAVEN_TOOL_NAME: 'maven'
  TCI_DEFAULT_MAVEN_SETTINGS_FILE_CONFIG_NAME: 'maven-settings'
  TCI_DEFAULT_GIT_CREDENTIAL: 'gitsshkey'


