security:
  realm: jenkins_database
  adminPassword: ${JENKINS_ADMIN_PASSWORD}

  remove_master_envvars:
  - '.*PASSWORD.*'

credentials:
  gitsshkey:
    type: sshkey
    description: gitsshkey
    username: gitsshkey
    passphrase:
    privatekey: |
      ${GIT_PRIVATE_KEY}
tools:
  installations:
    maven:
      type: maven
      installers:
        - id: '3.6.0'
clouds:
  tci-jnlp-nodes:
    type: docker
    dockerHostUri: 'unix:///var/run/docker.sock'
    templates:
      - name: tci-jnlp-node
        image: tikalci/tci-jnlp-node:latest
        labels:
          - tci-jnlp-node
        remoteFs: /home/jenkins
        jvmArgs: -Xmx1g
        volumes:
          - '/var/run/docker.sock:/var/run/docker.sock'
        instanceCap: '10'

pipeline_libraries:
  tci-library:
    source:
      remote: git@github.com:TikalCI/tci-library.git
      credentialsId: gitsshkey
    defaultVersion: ${TCI_LIBRARY_BRANCH}
    implicit: false
    allowVersionOverride: true
    includeInChangesets: true

